---
- hosts: webservers

  tasks:
    - name: installerime Apache2 Klient1(Debian) ja Klient2(CentOS)
      ansible.builtin.package:
        name: "{{ apache_paket }}"
        state: latest


    - name: Enable-me ja start-ime Apache (CentOS-il) ja (Debian-il)
      ansible.builtin.service:
        name: "{{ apache_paket }}"
        state: started
        enabled: true

    - name: Allow HTTP teenus CentOS-il firewall-is
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
      when: ansible_distribution == "CentOS"

    - name: Asendame Apache2 default index.html oma failiga
      ansible.builtin.template:
        src: index.html.j2
        dest: "{{ root_dest }}"
        force: true

    - name: Muudame /home/user/ kataloogi 천igused(711)
      file:
        path: /home/user/
        mode: 0711

    - name: Loome public_html kataloogi user-ile ja m채채rame 천igused(755)
      file:
        path: /home/user/public_html
        owner: user
        group: user
        mode: 0755
        state: directory

    - name: Lubame userdir Apache2 moodul Klient1(Debian)
      apache2_module:
        name: userdir
        state: present
      when: ansible_distribution == "Debian"
      notify: Restart Apache

    - name: Muudame userdir.conf *UserDir disabled* asendame *UserDir public_html*
      lineinfile:
        dest: "{{ asukoht_userdir_conf }}"
        regexp: '^\s*UserDir disabled'
        line: 'UserDir public_html'
      notify: Restart Apache

    - name: Paneme USER-le default index.html 
      ansible.builtin.template:
        src: user_index.html.j2
        dest: "{{ user_dest }}"
        force: true


  handlers:
    - name: Restart Apache
      ansible.builtin.service:
        name: "{{ apache_paket }}"
        state: restarted
